config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "home/index"
  resources :trips do
    resources :places
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :url, presence: true
  validates :name, presence: true

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :trip

  validates :date_visited, presence: true

  has_many :links, as: :linkable, dependent: :destroy

  accepts_nested_attributes_for :links

end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :places, dependent: :destroy
  has_many :links, as: :linkable, dependent: :destroy

  accepts_nested_attributes_for :places, allow_destroy: true
  accepts_nested_attributes_for :links, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :find_trip

  def index
    @places = @trip.places

    respond_to do |format|
      format.html do
        # Render the full HTML view for non-AJAX requests
        render :index
      end
      format.js do
        # Render a partial for AJAX requests
        render partial: "places/place", collection: @places
      end
    end
  end

def new
  @place = @trip.places.build
  @place.links.build
end

  def create
    @place = @trip.places.build(place_params)
    if @place.save
      redirect_to trip_places_path(@trip), notice: "Yay! Place was successfully created!"
    else
      render :new
    end
  end

  def edit
    @place = @trip.places.find(params[:id])
  end

  def update
    @place = @trip.places.find(params[:id])
    if @place.update(place_params)
      redirect_to trip_places_path(@trip), notice: "Yay! Place was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @place = @trip.places.find(params[:id])
    @place.destroy!
    redirect_to trip_places_path(@trip), notice: "Yay! Place was successfully deleted!"
  end

  private

  def find_trip
    @trip = Trip.find(params[:trip_id])
  end

  def place_params
    params.require(:place).permit(:name, :description, :date_visited, :trip_id, links_attributes: [:name, :url], links: [:name, :url])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show edit update destroy]

  # GET /trips or /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1 or /trips/1.json
  def show
    @trip = Trip.find(params[:id])
    @places = @trip.places
    @links = @trip.links # Fetch links associated with the trip
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips or /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to trip_url(@trip), notice: "Yay! Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trip_url(@trip), notice: "Yay! Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy!

    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
    def trip_params
    params.require(:trip).permit(:name, :description, :start_date, :end_date, links_attributes: [ :name, :url, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="bg-gray-800 sticky top-0">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
          </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <h3 class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"><%= link_to 'Home', root_path %></h3>
            <h3 class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"><%= link_to 'Trips', trips_path %></h3>
            <h3 class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"><%= link_to 'Add New Trip!', new_trip_path %></h3>
          </div>
        </div>
      </div>
    </div>
  </div>

    <div class="hidden sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
    <h3 class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium"><%= link_to 'Home', root_path %></h3>
    <h3 class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"><%= link_to 'Trips', trips_path %></h3>
    <h3 class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium"><%= link_to 'Add New Trip!', new_trip_path %></h3>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pushpin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag 'navbar' %>
    <%= javascript_include_tag 'modal' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <main class="container mx-auto mt-14 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: [@trip, place], local: true) do |form| %>

<form>
<div class="space-y-12">
<div class="border-b border-gray-900/10 pb-12">

<div class="m-2">
<h2 class="text-base font-semibold leading-7 text-gray-900"><%= form.label :name, "Place Name" %></h2>
<%= form.text_field :name %>
</div>

<div class="m-2">
<h2 class="text-base font-semibold leading-7 text-gray-900"><%= form.label :description, "Place Description" %></h2>
<p class="block w-full rounded-md border-0 text-gray-900 shadow-sm placeholder:text-gray-400 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"><%= form.text_area :description %></p>
<div>

<div>
  <h2 class="text-base font-semibold leading-7 text-gray-900">Add a Link!</h2>
  <%= form.fields_for :links, (link_form = @place.links.build) do |link_form| %>
    <div class="mb-4">
      <%= link_form.label :name, raw("<i class='fa-solid fa-link'></i> Name"), class: "block text-sm font-medium text-gray-700" %>
      <%= link_form.text_field :name, class: "mt-1 p-2", placeholder: "photo album, blog post..."%>
    </div>

    <div class="mb-4">
      <%= link_form.label :url, raw("<i class='fa-solid fa-link'></i> URL"), class: "block text-sm font-medium text-gray-700" %>
      <%= link_form.text_field :url, class: "mt-1 p-2", placeholder: "www.example.com..." %>
    </div>
  <% end %>
</div>

<div class="m-2">
<h2 class="text-base font-semibold leading-7 text-gray-900"><%= form.label :date_visited, "Date Visited" %></h2>
<%= form.date_field :date_visited %>
</div>


<div class="mt-6 flex items-center justify-end gap-x-6">
  <%= form.submit "Save Place!", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
</div>

</div>
</div>
</form>
<% end %>

app/views/places/_place.html.erb
<div class="max-md:mx-4 mt-4">
  <div class="text-2xl font-bold max-md:text-xl">
    <p><%= place.name %></p>
  </div>
  <div class="max-md:mx-2 max-md:my-2 max-md:p-2 max-md:bg-gray-100 max-md:rounded">
    <p><%= place.description %></p>
  </div>
  <div class="my-4 text-gray-500 font-semibold max-md:text-sm max-xl:text-lg">
    <p>Visited on: <%= place.date_visited.strftime("%B %d, %Y") %></p>
  </div>

  <!-- Display Links -->
  <div class="m-5">
<% place.links.each do |link| %>
  <div class="flex items-center mt-2">
    <%= raw("<i class='fa-solid fa-link block text-sm font-bold text-gray-700 m-2'></i>") %>
      <%= link_to link.name, link.url, target: "_blank", class: "font-semibold text-gray-700 text-gray-800 hover:underline hover:text-violet-700 hover:font-bold" %>
  </div>
<% end %>
</div>
</div>

app/views/places/edit.html.erb
<div class="flex flex-col">
<h1 class="text-3xl font-bold p-2 m-2">Edit Place</h1>

<%= render 'form', place: @place %>

<br>

<div>
  <%= link_to "Show Places!", @place, class: "text-sm font-semibold leading-6 text-gray-900" %> |
  <%= link_to "Back to Trips!", trips_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
</div>

</div>

app/views/places/index.html.erb
<div class="flex flex-col">
<h1 class="text-3xl font-bold mx-3 max-md:text-2xl">Places</h1>
<h2 class="text-2xl font-medium max-md:text-xl">visited on <%= link_to @trip.name, trip_path(@trip), class: "text-gray-800 hover:underline hover:text-violet-700 hover:font-bold" %> trip!</h2>

<div class="m-6 flex flex-col items-center justify-end gap-x-6">
<% if @trip.places.any? %>
  <!-- Display places here -->
  <% @trip.places.each do |place| %>
    <!-- Display individual place details as needed -->
 <%= render partial: "place", locals: { place: place } %>
  <% end %>
<% else %>
  <p class="text-base font-semibold leading-7 text-gray-900">Oops! There are no places on this trip!</p>
<% end %>
</div>

<div class="m-6 flex flex-col items-center justify-end gap-x-6">
  <%= link_to new_trip_place_path(@trip), class: "rounded-md bg-indigo-600 p-2 text-lg font-bold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
    <i class="fa-solid fa-location-crosshairs text-xl"></i>
    <i class="fa-solid fa-plus"></i>
  <% end %>
</div>

app/views/places/index.js.erb
document.getElementById("placesModalContent").innerHTML = "<%= j render partial: 'places/place', collection: @places %>";
modal.classList.remove("hidden");

app/views/places/new.html.erb
<div class="flex flex-col">
<h1 class="text-3xl font-bold p-2 m-2">New Place!</h1>

<%= render 'form', place: @place %>

<br>

<div>
  <%= link_to "Show Places!", trip_places_path(@trip), class: "text-sm font-semibold leading-6 text-gray-900" %> |
  <%= link_to "Back to Trips!", trips_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
</div>

</div>

app/views/places/show.html.erb
<div>
<h1><%= @place.name %></h1>
<p><%= @place.description %></p>
</div>

app/views/trips/_form.html.erb
<%= form_with(model: trip) do |form| %>
  <% if trip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="border-b border-gray-900/10 pb-12">
    <div class="m-2">
      <h2 class="text-base font-semibold leading-7 text-gray-900"><%= form.label :name, "Trip Name", style: "display: block" %></h2>
      <%= form.text_field :name %>
    </div>
    <div class="m-2">
      <h2 class="text-base font-semibold leading-7 text-gray-900"><%= form.label :start_date, "Trip Start", style: "display: block" %></h2>
      <%= form.date_field :start_date %>
    </div>

    <div class="m-2">
      <h2 class="text-base font-semibold leading-7 text-gray-900"><%= form.label :end_date, "Trip End", style: "display: block" %></h2>
      <%= form.date_field :end_date %>
    </div>
    <div class="m-2">
      <h2 class="text-base font-semibold leading-7 text-gray-900"><%= form.label :description, "Trip Description", style: "display: block" %></h2>
      <%= form.text_area :description %>
    </div>

  <div>
  <h2 class="text-base font-semibold leading-7 text-gray-900">Add a Link!</h2>
  <%= form.fields_for :links, (link_form = @trip.links.build) do |link_form| %>
    <div class="nested-fields">
      <div class="mb-4">
        <%= link_form.label :name, raw("<i class='fa-solid fa-link'></i> Name"), class: "block text-sm font-medium text-gray-700" %>
        <%= link_form.text_field :name, class: "mt-1 p-2", placeholder: "photo album, blog post..." %>
      </div>

      <div class="mb-4">
        <%= link_form.label :url, raw("<i class='fa-solid fa-link'></i> URL"), class: "block text-sm font-medium text-gray-700" %>
        <%= link_form.text_field :url, class: "mt-1 p-2", placeholder: "www.example.com..." %>
      </div>
    </div>
  <% end %>
</div>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= form.submit "Save Trip!", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  </div>
<% end %>

app/views/trips/_trip.html.erb
<div id="<%= dom_id trip %>" class="p-4">
  <div>
    <h2 class="block text-md font-medium leading-loose text-gray-900">Name:</h2>
    <%= trip.name %>
  </div>

  <div>
    <h2 class="block text-md font-medium leading-loose text-gray-900">Description:</h2>
    <div class="<%= 'line-clamp-1' if controller_name == 'trips' && action_name == 'index' %>">
  <%= trip.description %>
</div>
  </div>

  <div>
    <h2 class="block text-md font-medium leading-loose text-gray-900">Start date:</h2>
    <%= trip.start_date %>
  </div>

  <div>
    <h2 class="block text-md font-medium leading-loose text-gray-900">End date:</h2>
    <%= trip.end_date %>
  </div>

</div>

app/views/trips/edit.html.erb
<div class="flex flex-col">
<h1 class="text-3xl font-bold p-2 m-2">Edit Trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Show Trip!", @trip, class: "text-sm font-semibold leading-6 text-gray-900" %> |
  <%= link_to "Back to Trips!", trips_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
</div>

</div>

app/views/trips/index.html.erb
<div class="flex flex-col">
<p style="color: green"><%= notice %></p>

<h1 class="text-4xl font-bold p-2 m-auto">Trips</h1>

<div id="trips" class="grid lg:grid-cols-3 sm:grid-cols-2 gap-4">
  <% @trips.each do |trip| %>
    <div class="m-6 flex flex-col items-center border-2 border-slate-200 hover:border-4 hover:border-violet-700 hover:scale-110">
      <%= render trip %>
      <p class="m-4">
        <%= link_to "Show Trip!", trip, class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </p>
    </div>
  <% end %>
</div>

<div class="m-6 flex flex-col items-center justify-end gap-x-6">
<%= link_to "Add New Trip!", new_trip_path, class: "text-xl leading-6 text-gray-800 hover:underline hover:text-violet-700 hover:semibold" %>
</div>
</div>

app/views/trips/new.html.erb
<div class="flex flex-col">
<h1 class="text-3xl font-bold p-2 m-2">New Trip!</h1>

<%= render "form", trip: @trip %>

<br>

<div class="m-6 flex flex-col items-center justify-end gap-x-6 p-4">
  <%= link_to "Go Back!", trips_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
</div>
<div>

app/views/trips/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="flex flex-row max-md:flex-col">

<div>
<%= render @trip %>
</div>

<!-- Display Links -->
<div class="m-5">
  <% @links.each do |link| %>
    <div class="flex items-center mt-2">
      <%= raw("<i class='fa-solid fa-link block text-sm font-bold text-gray-700 m-2'></i>") %>
      <%= link_to link.name, link.url, target: "_blank", class: "font-semibold text-gray-700 text-gray-800 hover:underline hover:text-violet-700 hover:font-bold" %>
    </div>
  <% end %>
</div>

<div class="max-md:flex max-md:flex-col max-md:justify-center max-md:items-center">

<div class="border-2 border-slate-200 m-2">

<div class="m-3 border-b border-gray-900/10 pb-8">


<div>
  <p class="text-xl font-normal">Places on this trip:</p>
  <h2  class="block text-3xl text-center font-black leading-loose text-gray-900"><%= @places.count %><i class="fa-solid fa-location-crosshairs p-2 text-gray-600"></i></h2>
</div>

<div class="p-2">
  <%= button_to "Add Place!", new_trip_place_path(@trip), method: :get, class: "text-sm font-semibold leading-6 text-gray-900" %>
</div>

<div class="p-2 hidden md:block">
  <%= link_to trip_places_path(@trip), class: "text-sm font-semibold leading-6 text-gray-900" do %>
    Show Places!
  <% end %>
</div>

<div class="p-2 block md:hidden" id="openModal">
  <button class="text-xl font-semibold leading-6 text-gray-900" id="openModalButton">
    <i class="fa-solid fa-arrow-up-right-from-square"></i>
  </button>
</div>

</div>

<div class="m-4 flex items-center gap-x-6 p-4 max-md:justify-center">
  <%= link_to edit_trip_path(@trip), class: "text-3xl font-normal leading-6 text-gray-900" do %>
  <%= icon('fa-solid', 'pen-to-square') %>
<% end %> |
  <%= link_to "Go Back!", trips_path, class: "text-sm font-semibold leading-6 text-gray-900" %>

  <%= button_to @trip, method: :delete, class: "rounded-md bg-rose-600 px-3 py-2 text-3xl font-semibold text-white shadow-sm hover:bg-rose-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-rose-600" do %>
  <%= icon('fa-solid', 'trash') %>
<% end %>

</div>

</div>

</div>

</div>

<!-- Modal HTML -->
<div id="placesModal" class="max-md:fixed max-md:inset-0 max-md:bg-black max-md:bg-opacity-50 hidden">
  <div class="max-md:absolute max-md:top-1/2 max-md:left-1/2 max-md:transform -translate-x-1/2 -translate-y-1/2 max-md:w-full max-md:bg-white max-md:p-4 max-md:rounded" data-modal style="max-height: 80vh; overflow-y: auto;">
    <!-- Your modal content goes here -->
    <div id="placesModalContent">
  <%= render partial: "places/place", collection: @trip.places %>
</div>
    <button id="closeModal" class="mt-4 bg-indigo-600 text-white font-bold px-4 py-2 rounded-md shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Back!</button>
  </div>
</div>

<%= javascript_include_tag 'modal' %>